apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-app-account
  namespace: chat-app

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chat-app-role
  namespace: chat-app
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","watch","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list"]  
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  chat-app-binding
  namespace: chat-app
subjects:
- kind: ServiceAccount
  name: chat-app-account
  namespace: chat-app
roleRef:
  kind: Role
  name: chat-app-role
  apiGroup: rbac.authorization.k8s.io
