apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      serviceAccount: chat-app-account
      containers:
      - name: chat-api
        image: sesaquecruz/go-chat-api:v1.0.0
        resources:
          requests: 
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
        startupProbe:
          httpGet:
            path: /api/v1/healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /api/v1/healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /api/v1/healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
          successThreshold: 1
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: chat-api-secret
        - configMapRef:
            name: chat-api-cfgmap
