apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-api-hpa
  namespace: chat-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: chat-api
    kind: Deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
